title: Dr. Tobias Heycke
logo: img/th2.jpg
description: Postdoctoral researcher at GESIS - Leibniz Institute for the Social Sciences | Open Science Enthusiast
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
